//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
using System;
using System.ComponentModel.Composition;

namespace Bullsfirst.InterfaceOut.Oms.TradingServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", ConfigurationName="TradingServiceReference.TradingWebService")]
    public interface TradingWebService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="OpenNewAccount", ReplyAction="http://archfirst.org/bfoms/tradingservice.wsdl/TradingWebService/OpenNewAccountRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginOpenNewAccount(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OpenNewAccountRequest request, System.AsyncCallback callback, object asyncState);
        
        Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OpenNewAccountResponse EndOpenNewAccount(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="AddExternalAccount", ReplyAction="http://archfirst.org/bfoms/tradingservice.wsdl/TradingWebService/AddExternalAccou" +
            "ntResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginAddExternalAccount(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.AddExternalAccountRequest request, System.AsyncCallback callback, object asyncState);
        
        Bullsfirst.InterfaceOut.Oms.TradingServiceReference.AddExternalAccountResponse EndAddExternalAccount(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="TransferCash", ReplyAction="http://archfirst.org/bfoms/tradingservice.wsdl/TradingWebService/TransferCashResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginTransferCash(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferCashRequest request, System.AsyncCallback callback, object asyncState);
        
        Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferCashResponse EndTransferCash(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="TransferSecurities", ReplyAction="http://archfirst.org/bfoms/tradingservice.wsdl/TradingWebService/TransferSecuriti" +
            "esResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginTransferSecurities(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferSecuritiesRequest request, System.AsyncCallback callback, object asyncState);
        
        Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferSecuritiesResponse EndTransferSecurities(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="PlaceOrder", ReplyAction="http://archfirst.org/bfoms/tradingservice.wsdl/TradingWebService/PlaceOrderRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginPlaceOrder(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.PlaceOrderRequest request, System.AsyncCallback callback, object asyncState);
        
        Bullsfirst.InterfaceOut.Oms.TradingServiceReference.PlaceOrderResponse EndPlaceOrder(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetBrokerageAccountSummaries", ReplyAction="http://archfirst.org/bfoms/tradingservice.wsdl/TradingWebService/GetBrokerageAcco" +
            "untSummariesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetBrokerageAccountSummaries(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.GetBrokerageAccountSummariesRequest request, System.AsyncCallback callback, object asyncState);
        
        Bullsfirst.InterfaceOut.Oms.TradingServiceReference.GetBrokerageAccountSummariesResponse EndGetBrokerageAccountSummaries(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpenNewAccount", WrapperNamespace="http://archfirst.org/bfoms/tradingservice.wsdl", IsWrapped=true)]
    public partial class OpenNewAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AccountName;
        
        public OpenNewAccountRequest() {
        }
        
        public OpenNewAccountRequest(string AccountName) {
            this.AccountName = AccountName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpenNewAccountResponse", WrapperNamespace="http://archfirst.org/bfoms/tradingservice.wsdl", IsWrapped=true)]
    public partial class OpenNewAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long AccountId;
        
        public OpenNewAccountResponse() {
        }
        
        public OpenNewAccountResponse(long AccountId) {
            this.AccountId = AccountId;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl")]
    public partial class ExternalAccountParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string routingNumberField;
        
        private string accountNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RoutingNumber {
            get {
                return this.routingNumberField;
            }
            set {
                this.routingNumberField = value;
                this.RaisePropertyChanged("RoutingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("AccountNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl")]
    public partial class Position : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accountIdField;
        
        private string accountNameField;
        
        private string instrumentSymbolField;
        
        private string instrumentNameField;
        
        private long lotIdField;
        
        private string lotCreationTimeField;
        
        private Money lastTradeField;
        
        private Money marketValueField;
        
        private Money pricePaidField;
        
        private Money totalCostField;
        
        private Money gainField;
        
        private Position[] childField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
                this.RaisePropertyChanged("AccountId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
                this.RaisePropertyChanged("AccountName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string InstrumentSymbol {
            get {
                return this.instrumentSymbolField;
            }
            set {
                this.instrumentSymbolField = value;
                this.RaisePropertyChanged("InstrumentSymbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string InstrumentName {
            get {
                return this.instrumentNameField;
            }
            set {
                this.instrumentNameField = value;
                this.RaisePropertyChanged("InstrumentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long LotId {
            get {
                return this.lotIdField;
            }
            set {
                this.lotIdField = value;
                this.RaisePropertyChanged("LotId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LotCreationTime {
            get {
                return this.lotCreationTimeField;
            }
            set {
                this.lotCreationTimeField = value;
                this.RaisePropertyChanged("LotCreationTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public Money LastTrade {
            get {
                return this.lastTradeField;
            }
            set {
                this.lastTradeField = value;
                this.RaisePropertyChanged("LastTrade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public Money MarketValue {
            get {
                return this.marketValueField;
            }
            set {
                this.marketValueField = value;
                this.RaisePropertyChanged("MarketValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public Money PricePaid {
            get {
                return this.pricePaidField;
            }
            set {
                this.pricePaidField = value;
                this.RaisePropertyChanged("PricePaid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public Money TotalCost {
            get {
                return this.totalCostField;
            }
            set {
                this.totalCostField = value;
                this.RaisePropertyChanged("TotalCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public Money Gain {
            get {
                return this.gainField;
            }
            set {
                this.gainField = value;
                this.RaisePropertyChanged("Gain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Child", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public Position[] Child {
            get {
                return this.childField;
            }
            set {
                this.childField = value;
                this.RaisePropertyChanged("Child");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl")]
    public partial class Money : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal amountField;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl")]
    public partial class AccountSummary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private Money cashPositionField;
        
        private Money marketValueField;
        
        private bool editPermissionField;
        
        private bool tradePermissionField;
        
        private bool transferPermissionField;
        
        private Position[] positionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Money CashPosition {
            get {
                return this.cashPositionField;
            }
            set {
                this.cashPositionField = value;
                this.RaisePropertyChanged("CashPosition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Money MarketValue {
            get {
                return this.marketValueField;
            }
            set {
                this.marketValueField = value;
                this.RaisePropertyChanged("MarketValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool EditPermission {
            get {
                return this.editPermissionField;
            }
            set {
                this.editPermissionField = value;
                this.RaisePropertyChanged("EditPermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool TradePermission {
            get {
                return this.tradePermissionField;
            }
            set {
                this.tradePermissionField = value;
                this.RaisePropertyChanged("TradePermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool TransferPermission {
            get {
                return this.transferPermissionField;
            }
            set {
                this.transferPermissionField = value;
                this.RaisePropertyChanged("TransferPermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Position", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public Position[] Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("Position");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl")]
    public partial class OrderParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OrderSide sideField;
        
        private string symbolField;
        
        private decimal quantityField;
        
        private OrderType typeField;
        
        private Money limitPriceField;
        
        private OrderTerm termField;
        
        private bool allOrNoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OrderSide Side {
            get {
                return this.sideField;
            }
            set {
                this.sideField = value;
                this.RaisePropertyChanged("Side");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
                this.RaisePropertyChanged("Symbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public OrderType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public Money LimitPrice {
            get {
                return this.limitPriceField;
            }
            set {
                this.limitPriceField = value;
                this.RaisePropertyChanged("LimitPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public OrderTerm Term {
            get {
                return this.termField;
            }
            set {
                this.termField = value;
                this.RaisePropertyChanged("Term");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool AllOrNone {
            get {
                return this.allOrNoneField;
            }
            set {
                this.allOrNoneField = value;
                this.RaisePropertyChanged("AllOrNone");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl")]
    public enum OrderSide {
        
        /// <remarks/>
        Buy,
        
        /// <remarks/>
        Sell,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl")]
    public enum OrderType {
        
        /// <remarks/>
        Market,
        
        /// <remarks/>
        Limit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl")]
    public enum OrderTerm {
        
        /// <remarks/>
        GoodForTheDay,
        
        /// <remarks/>
        GoodTilCanceled,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddExternalAccount", WrapperNamespace="http://archfirst.org/bfoms/tradingservice.wsdl", IsWrapped=true)]
    public partial class AddExternalAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bullsfirst.InterfaceOut.Oms.TradingServiceReference.ExternalAccountParams ExternalAccountParams;
        
        public AddExternalAccountRequest() {
        }
        
        public AddExternalAccountRequest(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.ExternalAccountParams ExternalAccountParams) {
            this.ExternalAccountParams = ExternalAccountParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddExternalAccountResponse", WrapperNamespace="http://archfirst.org/bfoms/tradingservice.wsdl", IsWrapped=true)]
    public partial class AddExternalAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long AccountId;
        
        public AddExternalAccountResponse() {
        }
        
        public AddExternalAccountResponse(long AccountId) {
            this.AccountId = AccountId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransferCash", WrapperNamespace="http://archfirst.org/bfoms/tradingservice.wsdl", IsWrapped=true)]
    public partial class TransferCashRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bullsfirst.InterfaceOut.Oms.TradingServiceReference.Money Amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long FromAccountId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long ToAccountId;
        
        public TransferCashRequest() {
        }
        
        public TransferCashRequest(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.Money Amount, long FromAccountId, long ToAccountId) {
            this.Amount = Amount;
            this.FromAccountId = FromAccountId;
            this.ToAccountId = ToAccountId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransferCashResponse", WrapperNamespace="http://archfirst.org/bfoms/tradingservice.wsdl", IsWrapped=true)]
    public partial class TransferCashResponse {
        
        public TransferCashResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransferSecurities", WrapperNamespace="http://archfirst.org/bfoms/tradingservice.wsdl", IsWrapped=true)]
    public partial class TransferSecuritiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Symbol;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Quantity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bullsfirst.InterfaceOut.Oms.TradingServiceReference.Money PricePaidPerShare;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long FromAccountId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long ToAccountId;
        
        public TransferSecuritiesRequest() {
        }
        
        public TransferSecuritiesRequest(string Symbol, decimal Quantity, Bullsfirst.InterfaceOut.Oms.TradingServiceReference.Money PricePaidPerShare, long FromAccountId, long ToAccountId) {
            this.Symbol = Symbol;
            this.Quantity = Quantity;
            this.PricePaidPerShare = PricePaidPerShare;
            this.FromAccountId = FromAccountId;
            this.ToAccountId = ToAccountId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransferSecuritiesResponse", WrapperNamespace="http://archfirst.org/bfoms/tradingservice.wsdl", IsWrapped=true)]
    public partial class TransferSecuritiesResponse {
        
        public TransferSecuritiesResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PlaceOrder", WrapperNamespace="http://archfirst.org/bfoms/tradingservice.wsdl", IsWrapped=true)]
    public partial class PlaceOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long BrokerageAccountId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OrderParams OrderParams;
        
        public PlaceOrderRequest() {
        }
        
        public PlaceOrderRequest(long BrokerageAccountId, Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OrderParams OrderParams) {
            this.BrokerageAccountId = BrokerageAccountId;
            this.OrderParams = OrderParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PlaceOrderResponse", WrapperNamespace="http://archfirst.org/bfoms/tradingservice.wsdl", IsWrapped=true)]
    public partial class PlaceOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long OrderId;
        
        public PlaceOrderResponse() {
        }
        
        public PlaceOrderResponse(long OrderId) {
            this.OrderId = OrderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBrokerageAccountSummaries", WrapperNamespace="http://archfirst.org/bfoms/tradingservice.wsdl", IsWrapped=true)]
    public partial class GetBrokerageAccountSummariesRequest {
        
        public GetBrokerageAccountSummariesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBrokerageAccountSummariesResponse", WrapperNamespace="http://archfirst.org/bfoms/tradingservice.wsdl", IsWrapped=true)]
    public partial class GetBrokerageAccountSummariesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/tradingservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("AccountSummary", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AccountSummary[] AccountSummary;
        
        public GetBrokerageAccountSummariesResponse() {
        }
        
        public GetBrokerageAccountSummariesResponse(AccountSummary[] AccountSummary) {
            this.AccountSummary = AccountSummary;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TradingWebServiceChannel : Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OpenNewAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public OpenNewAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddExternalAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddExternalAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlaceOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PlaceOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBrokerageAccountSummariesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBrokerageAccountSummariesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AccountSummary[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AccountSummary[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TradingWebServiceClient : System.ServiceModel.ClientBase<Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService>, Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService {
        
        private BeginOperationDelegate onBeginOpenNewAccountDelegate;
        
        private EndOperationDelegate onEndOpenNewAccountDelegate;
        
        private System.Threading.SendOrPostCallback onOpenNewAccountCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddExternalAccountDelegate;
        
        private EndOperationDelegate onEndAddExternalAccountDelegate;
        
        private System.Threading.SendOrPostCallback onAddExternalAccountCompletedDelegate;
        
        private BeginOperationDelegate onBeginTransferCashDelegate;
        
        private EndOperationDelegate onEndTransferCashDelegate;
        
        private System.Threading.SendOrPostCallback onTransferCashCompletedDelegate;
        
        private BeginOperationDelegate onBeginTransferSecuritiesDelegate;
        
        private EndOperationDelegate onEndTransferSecuritiesDelegate;
        
        private System.Threading.SendOrPostCallback onTransferSecuritiesCompletedDelegate;
        
        private BeginOperationDelegate onBeginPlaceOrderDelegate;
        
        private EndOperationDelegate onEndPlaceOrderDelegate;
        
        private System.Threading.SendOrPostCallback onPlaceOrderCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetBrokerageAccountSummariesDelegate;
        
        private EndOperationDelegate onEndGetBrokerageAccountSummariesDelegate;
        
        private System.Threading.SendOrPostCallback onGetBrokerageAccountSummariesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public TradingWebServiceClient() {
        }
        
        public TradingWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TradingWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradingWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradingWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<OpenNewAccountCompletedEventArgs> OpenNewAccountCompleted;
        
        public event System.EventHandler<AddExternalAccountCompletedEventArgs> AddExternalAccountCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> TransferCashCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> TransferSecuritiesCompleted;
        
        public event System.EventHandler<PlaceOrderCompletedEventArgs> PlaceOrderCompleted;
        
        public event System.EventHandler<GetBrokerageAccountSummariesCompletedEventArgs> GetBrokerageAccountSummariesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService.BeginOpenNewAccount(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OpenNewAccountRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginOpenNewAccount(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginOpenNewAccount(string AccountName, System.AsyncCallback callback, object asyncState) {
            Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OpenNewAccountRequest inValue = new Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OpenNewAccountRequest();
            inValue.AccountName = AccountName;
            return ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService)(this)).BeginOpenNewAccount(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OpenNewAccountResponse Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService.EndOpenNewAccount(System.IAsyncResult result) {
            return base.Channel.EndOpenNewAccount(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private long EndOpenNewAccount(System.IAsyncResult result) {
            Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OpenNewAccountResponse retVal = ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService)(this)).EndOpenNewAccount(result);
            return retVal.AccountId;
        }
        
        private System.IAsyncResult OnBeginOpenNewAccount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string AccountName = ((string)(inValues[0]));
            return this.BeginOpenNewAccount(AccountName, callback, asyncState);
        }
        
        private object[] OnEndOpenNewAccount(System.IAsyncResult result) {
            long retVal = this.EndOpenNewAccount(result);
            return new object[] {
                    retVal};
        }
        
        private void OnOpenNewAccountCompleted(object state) {
            if ((this.OpenNewAccountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenNewAccountCompleted(this, new OpenNewAccountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenNewAccountAsync(string AccountName) {
            this.OpenNewAccountAsync(AccountName, null);
        }
        
        public void OpenNewAccountAsync(string AccountName, object userState) {
            if ((this.onBeginOpenNewAccountDelegate == null)) {
                this.onBeginOpenNewAccountDelegate = new BeginOperationDelegate(this.OnBeginOpenNewAccount);
            }
            if ((this.onEndOpenNewAccountDelegate == null)) {
                this.onEndOpenNewAccountDelegate = new EndOperationDelegate(this.OnEndOpenNewAccount);
            }
            if ((this.onOpenNewAccountCompletedDelegate == null)) {
                this.onOpenNewAccountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenNewAccountCompleted);
            }
            base.InvokeAsync(this.onBeginOpenNewAccountDelegate, new object[] {
                        AccountName}, this.onEndOpenNewAccountDelegate, this.onOpenNewAccountCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService.BeginAddExternalAccount(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.AddExternalAccountRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddExternalAccount(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginAddExternalAccount(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.ExternalAccountParams ExternalAccountParams, System.AsyncCallback callback, object asyncState) {
            Bullsfirst.InterfaceOut.Oms.TradingServiceReference.AddExternalAccountRequest inValue = new Bullsfirst.InterfaceOut.Oms.TradingServiceReference.AddExternalAccountRequest();
            inValue.ExternalAccountParams = ExternalAccountParams;
            return ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService)(this)).BeginAddExternalAccount(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bullsfirst.InterfaceOut.Oms.TradingServiceReference.AddExternalAccountResponse Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService.EndAddExternalAccount(System.IAsyncResult result) {
            return base.Channel.EndAddExternalAccount(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private long EndAddExternalAccount(System.IAsyncResult result) {
            Bullsfirst.InterfaceOut.Oms.TradingServiceReference.AddExternalAccountResponse retVal = ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService)(this)).EndAddExternalAccount(result);
            return retVal.AccountId;
        }
        
        private System.IAsyncResult OnBeginAddExternalAccount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Bullsfirst.InterfaceOut.Oms.TradingServiceReference.ExternalAccountParams ExternalAccountParams = ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.ExternalAccountParams)(inValues[0]));
            return this.BeginAddExternalAccount(ExternalAccountParams, callback, asyncState);
        }
        
        private object[] OnEndAddExternalAccount(System.IAsyncResult result) {
            long retVal = this.EndAddExternalAccount(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddExternalAccountCompleted(object state) {
            if ((this.AddExternalAccountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddExternalAccountCompleted(this, new AddExternalAccountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddExternalAccountAsync(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.ExternalAccountParams ExternalAccountParams) {
            this.AddExternalAccountAsync(ExternalAccountParams, null);
        }
        
        public void AddExternalAccountAsync(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.ExternalAccountParams ExternalAccountParams, object userState) {
            if ((this.onBeginAddExternalAccountDelegate == null)) {
                this.onBeginAddExternalAccountDelegate = new BeginOperationDelegate(this.OnBeginAddExternalAccount);
            }
            if ((this.onEndAddExternalAccountDelegate == null)) {
                this.onEndAddExternalAccountDelegate = new EndOperationDelegate(this.OnEndAddExternalAccount);
            }
            if ((this.onAddExternalAccountCompletedDelegate == null)) {
                this.onAddExternalAccountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddExternalAccountCompleted);
            }
            base.InvokeAsync(this.onBeginAddExternalAccountDelegate, new object[] {
                        ExternalAccountParams}, this.onEndAddExternalAccountDelegate, this.onAddExternalAccountCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService.BeginTransferCash(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferCashRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTransferCash(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginTransferCash(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.Money Amount, long FromAccountId, long ToAccountId, System.AsyncCallback callback, object asyncState) {
            Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferCashRequest inValue = new Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferCashRequest();
            inValue.Amount = Amount;
            inValue.FromAccountId = FromAccountId;
            inValue.ToAccountId = ToAccountId;
            return ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService)(this)).BeginTransferCash(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferCashResponse Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService.EndTransferCash(System.IAsyncResult result) {
            return base.Channel.EndTransferCash(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndTransferCash(System.IAsyncResult result) {
            Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferCashResponse retVal = ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService)(this)).EndTransferCash(result);
        }
        
        private System.IAsyncResult OnBeginTransferCash(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Bullsfirst.InterfaceOut.Oms.TradingServiceReference.Money Amount = ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.Money)(inValues[0]));
            long FromAccountId = ((long)(inValues[1]));
            long ToAccountId = ((long)(inValues[2]));
            return this.BeginTransferCash(Amount, FromAccountId, ToAccountId, callback, asyncState);
        }
        
        private object[] OnEndTransferCash(System.IAsyncResult result) {
            this.EndTransferCash(result);
            return null;
        }
        
        private void OnTransferCashCompleted(object state) {
            if ((this.TransferCashCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TransferCashCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TransferCashAsync(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.Money Amount, long FromAccountId, long ToAccountId) {
            this.TransferCashAsync(Amount, FromAccountId, ToAccountId, null);
        }
        
        public void TransferCashAsync(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.Money Amount, long FromAccountId, long ToAccountId, object userState) {
            if ((this.onBeginTransferCashDelegate == null)) {
                this.onBeginTransferCashDelegate = new BeginOperationDelegate(this.OnBeginTransferCash);
            }
            if ((this.onEndTransferCashDelegate == null)) {
                this.onEndTransferCashDelegate = new EndOperationDelegate(this.OnEndTransferCash);
            }
            if ((this.onTransferCashCompletedDelegate == null)) {
                this.onTransferCashCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTransferCashCompleted);
            }
            base.InvokeAsync(this.onBeginTransferCashDelegate, new object[] {
                        Amount,
                        FromAccountId,
                        ToAccountId}, this.onEndTransferCashDelegate, this.onTransferCashCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService.BeginTransferSecurities(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferSecuritiesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTransferSecurities(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginTransferSecurities(string Symbol, decimal Quantity, Bullsfirst.InterfaceOut.Oms.TradingServiceReference.Money PricePaidPerShare, long FromAccountId, long ToAccountId, System.AsyncCallback callback, object asyncState) {
            Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferSecuritiesRequest inValue = new Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferSecuritiesRequest();
            inValue.Symbol = Symbol;
            inValue.Quantity = Quantity;
            inValue.PricePaidPerShare = PricePaidPerShare;
            inValue.FromAccountId = FromAccountId;
            inValue.ToAccountId = ToAccountId;
            return ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService)(this)).BeginTransferSecurities(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferSecuritiesResponse Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService.EndTransferSecurities(System.IAsyncResult result) {
            return base.Channel.EndTransferSecurities(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndTransferSecurities(System.IAsyncResult result) {
            Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferSecuritiesResponse retVal = ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService)(this)).EndTransferSecurities(result);
        }
        
        private System.IAsyncResult OnBeginTransferSecurities(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Symbol = ((string)(inValues[0]));
            decimal Quantity = ((decimal)(inValues[1]));
            Bullsfirst.InterfaceOut.Oms.TradingServiceReference.Money PricePaidPerShare = ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.Money)(inValues[2]));
            long FromAccountId = ((long)(inValues[3]));
            long ToAccountId = ((long)(inValues[4]));
            return this.BeginTransferSecurities(Symbol, Quantity, PricePaidPerShare, FromAccountId, ToAccountId, callback, asyncState);
        }
        
        private object[] OnEndTransferSecurities(System.IAsyncResult result) {
            this.EndTransferSecurities(result);
            return null;
        }
        
        private void OnTransferSecuritiesCompleted(object state) {
            if ((this.TransferSecuritiesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TransferSecuritiesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TransferSecuritiesAsync(string Symbol, decimal Quantity, Bullsfirst.InterfaceOut.Oms.TradingServiceReference.Money PricePaidPerShare, long FromAccountId, long ToAccountId) {
            this.TransferSecuritiesAsync(Symbol, Quantity, PricePaidPerShare, FromAccountId, ToAccountId, null);
        }
        
        public void TransferSecuritiesAsync(string Symbol, decimal Quantity, Bullsfirst.InterfaceOut.Oms.TradingServiceReference.Money PricePaidPerShare, long FromAccountId, long ToAccountId, object userState) {
            if ((this.onBeginTransferSecuritiesDelegate == null)) {
                this.onBeginTransferSecuritiesDelegate = new BeginOperationDelegate(this.OnBeginTransferSecurities);
            }
            if ((this.onEndTransferSecuritiesDelegate == null)) {
                this.onEndTransferSecuritiesDelegate = new EndOperationDelegate(this.OnEndTransferSecurities);
            }
            if ((this.onTransferSecuritiesCompletedDelegate == null)) {
                this.onTransferSecuritiesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTransferSecuritiesCompleted);
            }
            base.InvokeAsync(this.onBeginTransferSecuritiesDelegate, new object[] {
                        Symbol,
                        Quantity,
                        PricePaidPerShare,
                        FromAccountId,
                        ToAccountId}, this.onEndTransferSecuritiesDelegate, this.onTransferSecuritiesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService.BeginPlaceOrder(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.PlaceOrderRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPlaceOrder(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginPlaceOrder(long BrokerageAccountId, Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OrderParams OrderParams, System.AsyncCallback callback, object asyncState) {
            Bullsfirst.InterfaceOut.Oms.TradingServiceReference.PlaceOrderRequest inValue = new Bullsfirst.InterfaceOut.Oms.TradingServiceReference.PlaceOrderRequest();
            inValue.BrokerageAccountId = BrokerageAccountId;
            inValue.OrderParams = OrderParams;
            return ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService)(this)).BeginPlaceOrder(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bullsfirst.InterfaceOut.Oms.TradingServiceReference.PlaceOrderResponse Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService.EndPlaceOrder(System.IAsyncResult result) {
            return base.Channel.EndPlaceOrder(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private long EndPlaceOrder(System.IAsyncResult result) {
            Bullsfirst.InterfaceOut.Oms.TradingServiceReference.PlaceOrderResponse retVal = ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService)(this)).EndPlaceOrder(result);
            return retVal.OrderId;
        }
        
        private System.IAsyncResult OnBeginPlaceOrder(object[] inValues, System.AsyncCallback callback, object asyncState) {
            long BrokerageAccountId = ((long)(inValues[0]));
            Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OrderParams OrderParams = ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OrderParams)(inValues[1]));
            return this.BeginPlaceOrder(BrokerageAccountId, OrderParams, callback, asyncState);
        }
        
        private object[] OnEndPlaceOrder(System.IAsyncResult result) {
            long retVal = this.EndPlaceOrder(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPlaceOrderCompleted(object state) {
            if ((this.PlaceOrderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PlaceOrderCompleted(this, new PlaceOrderCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PlaceOrderAsync(long BrokerageAccountId, Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OrderParams OrderParams) {
            this.PlaceOrderAsync(BrokerageAccountId, OrderParams, null);
        }
        
        public void PlaceOrderAsync(long BrokerageAccountId, Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OrderParams OrderParams, object userState) {
            if ((this.onBeginPlaceOrderDelegate == null)) {
                this.onBeginPlaceOrderDelegate = new BeginOperationDelegate(this.OnBeginPlaceOrder);
            }
            if ((this.onEndPlaceOrderDelegate == null)) {
                this.onEndPlaceOrderDelegate = new EndOperationDelegate(this.OnEndPlaceOrder);
            }
            if ((this.onPlaceOrderCompletedDelegate == null)) {
                this.onPlaceOrderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPlaceOrderCompleted);
            }
            base.InvokeAsync(this.onBeginPlaceOrderDelegate, new object[] {
                        BrokerageAccountId,
                        OrderParams}, this.onEndPlaceOrderDelegate, this.onPlaceOrderCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService.BeginGetBrokerageAccountSummaries(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.GetBrokerageAccountSummariesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBrokerageAccountSummaries(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetBrokerageAccountSummaries(System.AsyncCallback callback, object asyncState) {
            Bullsfirst.InterfaceOut.Oms.TradingServiceReference.GetBrokerageAccountSummariesRequest inValue = new Bullsfirst.InterfaceOut.Oms.TradingServiceReference.GetBrokerageAccountSummariesRequest();
            return ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService)(this)).BeginGetBrokerageAccountSummaries(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bullsfirst.InterfaceOut.Oms.TradingServiceReference.GetBrokerageAccountSummariesResponse Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService.EndGetBrokerageAccountSummaries(System.IAsyncResult result) {
            return base.Channel.EndGetBrokerageAccountSummaries(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private AccountSummary[] EndGetBrokerageAccountSummaries(System.IAsyncResult result) {
            Bullsfirst.InterfaceOut.Oms.TradingServiceReference.GetBrokerageAccountSummariesResponse retVal = ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService)(this)).EndGetBrokerageAccountSummaries(result);
            return retVal.AccountSummary;
        }
        
        private System.IAsyncResult OnBeginGetBrokerageAccountSummaries(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetBrokerageAccountSummaries(callback, asyncState);
        }
        
        private object[] OnEndGetBrokerageAccountSummaries(System.IAsyncResult result) {
            AccountSummary[] retVal = this.EndGetBrokerageAccountSummaries(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBrokerageAccountSummariesCompleted(object state) {
            if ((this.GetBrokerageAccountSummariesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBrokerageAccountSummariesCompleted(this, new GetBrokerageAccountSummariesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBrokerageAccountSummariesAsync() {
            this.GetBrokerageAccountSummariesAsync(null);
        }
        
        public void GetBrokerageAccountSummariesAsync(object userState) {
            if ((this.onBeginGetBrokerageAccountSummariesDelegate == null)) {
                this.onBeginGetBrokerageAccountSummariesDelegate = new BeginOperationDelegate(this.OnBeginGetBrokerageAccountSummaries);
            }
            if ((this.onEndGetBrokerageAccountSummariesDelegate == null)) {
                this.onEndGetBrokerageAccountSummariesDelegate = new EndOperationDelegate(this.OnEndGetBrokerageAccountSummaries);
            }
            if ((this.onGetBrokerageAccountSummariesCompletedDelegate == null)) {
                this.onGetBrokerageAccountSummariesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBrokerageAccountSummariesCompleted);
            }
            base.InvokeAsync(this.onBeginGetBrokerageAccountSummariesDelegate, null, this.onEndGetBrokerageAccountSummariesDelegate, this.onGetBrokerageAccountSummariesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService CreateChannel() {
            return new TradingWebServiceClientChannel(this);
        }
        
        private class TradingWebServiceClientChannel : ChannelBase<Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService>, Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService {
            
            public TradingWebServiceClientChannel(System.ServiceModel.ClientBase<Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TradingWebService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginOpenNewAccount(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OpenNewAccountRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("OpenNewAccount", _args, callback, asyncState);
                return _result;
            }
            
            public Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OpenNewAccountResponse EndOpenNewAccount(System.IAsyncResult result) {
                object[] _args = new object[0];
                Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OpenNewAccountResponse _result = ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.OpenNewAccountResponse)(base.EndInvoke("OpenNewAccount", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddExternalAccount(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.AddExternalAccountRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("AddExternalAccount", _args, callback, asyncState);
                return _result;
            }
            
            public Bullsfirst.InterfaceOut.Oms.TradingServiceReference.AddExternalAccountResponse EndAddExternalAccount(System.IAsyncResult result) {
                object[] _args = new object[0];
                Bullsfirst.InterfaceOut.Oms.TradingServiceReference.AddExternalAccountResponse _result = ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.AddExternalAccountResponse)(base.EndInvoke("AddExternalAccount", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginTransferCash(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferCashRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("TransferCash", _args, callback, asyncState);
                return _result;
            }
            
            public Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferCashResponse EndTransferCash(System.IAsyncResult result) {
                object[] _args = new object[0];
                Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferCashResponse _result = ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferCashResponse)(base.EndInvoke("TransferCash", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginTransferSecurities(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferSecuritiesRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("TransferSecurities", _args, callback, asyncState);
                return _result;
            }
            
            public Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferSecuritiesResponse EndTransferSecurities(System.IAsyncResult result) {
                object[] _args = new object[0];
                Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferSecuritiesResponse _result = ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.TransferSecuritiesResponse)(base.EndInvoke("TransferSecurities", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPlaceOrder(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.PlaceOrderRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("PlaceOrder", _args, callback, asyncState);
                return _result;
            }
            
            public Bullsfirst.InterfaceOut.Oms.TradingServiceReference.PlaceOrderResponse EndPlaceOrder(System.IAsyncResult result) {
                object[] _args = new object[0];
                Bullsfirst.InterfaceOut.Oms.TradingServiceReference.PlaceOrderResponse _result = ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.PlaceOrderResponse)(base.EndInvoke("PlaceOrder", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetBrokerageAccountSummaries(Bullsfirst.InterfaceOut.Oms.TradingServiceReference.GetBrokerageAccountSummariesRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetBrokerageAccountSummaries", _args, callback, asyncState);
                return _result;
            }
            
            public Bullsfirst.InterfaceOut.Oms.TradingServiceReference.GetBrokerageAccountSummariesResponse EndGetBrokerageAccountSummaries(System.IAsyncResult result) {
                object[] _args = new object[0];
                Bullsfirst.InterfaceOut.Oms.TradingServiceReference.GetBrokerageAccountSummariesResponse _result = ((Bullsfirst.InterfaceOut.Oms.TradingServiceReference.GetBrokerageAccountSummariesResponse)(base.EndInvoke("GetBrokerageAccountSummaries", _args, result)));
                return _result;
            }
        }
    }

    public interface ITradingServiceAsync : TradingWebService
    {
        void OpenNewAccountAsync(string AccountName);
        void AddExternalAccountAsync(ExternalAccountParams ExternalAccountParams);
        void TransferCashAsync(Money Amount, long FromAccountId, long ToAccountId);
        void TransferSecuritiesAsync(
            string Symbol, decimal Quantity, Money PricePaidPerShare,
            long FromAccountId, long ToAccountId);
        void PlaceOrderAsync(long BrokerageAccountId, OrderParams OrderParams);
        void GetBrokerageAccountSummariesAsync();

        event EventHandler<OpenNewAccountCompletedEventArgs> OpenNewAccountCompleted;
        event EventHandler<AddExternalAccountCompletedEventArgs> AddExternalAccountCompleted;
        event EventHandler<System.ComponentModel.AsyncCompletedEventArgs> TransferCashCompleted;
        event EventHandler<System.ComponentModel.AsyncCompletedEventArgs> TransferSecuritiesCompleted;
        event EventHandler<PlaceOrderCompletedEventArgs> PlaceOrderCompleted;
        event EventHandler<GetBrokerageAccountSummariesCompletedEventArgs> GetBrokerageAccountSummariesCompleted;
        event EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        event EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    }

    [Export(typeof(ITradingServiceAsync))]
    [PartCreationPolicy(CreationPolicy.NonShared)]
    public partial class TradingWebServiceClient : ITradingServiceAsync
    {
    }
}
