//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://archfirst.org/bfexch/marketdataservice.wsdl", ConfigurationName="MarketDataServiceReference.MarketDataWebService")]
    public interface MarketDataWebService {
        
        // CODEGEN: Parameter 'MarketPrice' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="GetMarketPrices", ReplyAction="http://archfirst.org/bfexch/marketdataservice.wsdl/MarketDataWebService/GetMarket" +
            "PricesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="MarketPrice")]
        Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.GetMarketPricesResponse GetMarketPrices(Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.GetMarketPricesRequest request);
        
        // CODEGEN: Parameter 'MarketPrice' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="GetMarketPrice", ReplyAction="http://archfirst.org/bfexch/marketdataservice.wsdl/MarketDataWebService/GetMarket" +
            "PriceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="MarketPrice")]
        Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.GetMarketPriceResponse GetMarketPrice(Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.GetMarketPriceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://archfirst.org/bfexch/marketdataservice.wsdl")]
    public partial class MarketPrice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string symbolField;
        
        private Money priceField;
        
        private System.DateTime effectiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
                this.RaisePropertyChanged("Symbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Money Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime Effective {
            get {
                return this.effectiveField;
            }
            set {
                this.effectiveField = value;
                this.RaisePropertyChanged("Effective");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://archfirst.org/bfexch/marketdataservice.wsdl")]
    public partial class Money : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal amountField;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMarketPrices", WrapperNamespace="http://archfirst.org/bfexch/marketdataservice.wsdl", IsWrapped=true)]
    public partial class GetMarketPricesRequest {
        
        public GetMarketPricesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMarketPricesResponse", WrapperNamespace="http://archfirst.org/bfexch/marketdataservice.wsdl", IsWrapped=true)]
    public partial class GetMarketPricesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfexch/marketdataservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MarketPrice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MarketPrice[] MarketPrice;
        
        public GetMarketPricesResponse() {
        }
        
        public GetMarketPricesResponse(MarketPrice[] MarketPrice) {
            this.MarketPrice = MarketPrice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMarketPrice", WrapperNamespace="http://archfirst.org/bfexch/marketdataservice.wsdl", IsWrapped=true)]
    public partial class GetMarketPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfexch/marketdataservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Symbol;
        
        public GetMarketPriceRequest() {
        }
        
        public GetMarketPriceRequest(string Symbol) {
            this.Symbol = Symbol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMarketPriceResponse", WrapperNamespace="http://archfirst.org/bfexch/marketdataservice.wsdl", IsWrapped=true)]
    public partial class GetMarketPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfexch/marketdataservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.MarketPrice MarketPrice;
        
        public GetMarketPriceResponse() {
        }
        
        public GetMarketPriceResponse(Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.MarketPrice MarketPrice) {
            this.MarketPrice = MarketPrice;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MarketDataWebServiceChannel : Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.MarketDataWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MarketDataWebServiceClient : System.ServiceModel.ClientBase<Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.MarketDataWebService>, Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.MarketDataWebService {
        
        public MarketDataWebServiceClient() {
        }
        
        public MarketDataWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MarketDataWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarketDataWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarketDataWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.GetMarketPricesResponse Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.MarketDataWebService.GetMarketPrices(Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.GetMarketPricesRequest request) {
            return base.Channel.GetMarketPrices(request);
        }
        
        public MarketPrice[] GetMarketPrices() {
            Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.GetMarketPricesRequest inValue = new Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.GetMarketPricesRequest();
            Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.GetMarketPricesResponse retVal = ((Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.MarketDataWebService)(this)).GetMarketPrices(inValue);
            return retVal.MarketPrice;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.GetMarketPriceResponse Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.MarketDataWebService.GetMarketPrice(Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.GetMarketPriceRequest request) {
            return base.Channel.GetMarketPrice(request);
        }
        
        public Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.MarketPrice GetMarketPrice(string Symbol) {
            Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.GetMarketPriceRequest inValue = new Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.GetMarketPriceRequest();
            inValue.Symbol = Symbol;
            Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.GetMarketPriceResponse retVal = ((Bullsfirst.InterfaceOut.Oms.MarketDataServiceReference.MarketDataWebService)(this)).GetMarketPrice(inValue);
            return retVal.MarketPrice;
        }
    }
}
