//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
using System;
using System.ComponentModel.Composition;

namespace Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://archfirst.org/bfoms/referencedataservice.wsdl", ConfigurationName="ReferenceDataServiceReference.ReferenceDataWebService")]
    public interface ReferenceDataWebService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="Lookup", ReplyAction="http://archfirst.org/bfoms/referencedataservice.wsdl/ReferenceDataWebService/Look" +
            "upResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginLookup(Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupRequest request, System.AsyncCallback callback, object asyncState);
        
        Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupResponse EndLookup(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetInstruments", ReplyAction="http://archfirst.org/bfoms/referencedataservice.wsdl/ReferenceDataWebService/GetI" +
            "nstrumentsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetInstruments(Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsRequest request, System.AsyncCallback callback, object asyncState);
        
        Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsResponse EndGetInstruments(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://archfirst.org/bfoms/referencedataservice.wsdl")]
    public partial class Instrument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string symbolField;
        
        private string nameField;
        
        private string exchangeField;

        // Manually override so that AutoCompleteBox picks only the symbol when a dropdown is selected
        public override string ToString()
        {
            return Symbol;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
                this.RaisePropertyChanged("Symbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Exchange {
            get {
                return this.exchangeField;
            }
            set {
                this.exchangeField = value;
                this.RaisePropertyChanged("Exchange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Lookup", WrapperNamespace="http://archfirst.org/bfoms/referencedataservice.wsdl", IsWrapped=true)]
    public partial class LookupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/referencedataservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Symbol;
        
        public LookupRequest() {
        }
        
        public LookupRequest(string Symbol) {
            this.Symbol = Symbol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LookupResponse", WrapperNamespace="http://archfirst.org/bfoms/referencedataservice.wsdl", IsWrapped=true)]
    public partial class LookupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/referencedataservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.Instrument Instrument;
        
        public LookupResponse() {
        }
        
        public LookupResponse(Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.Instrument Instrument) {
            this.Instrument = Instrument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInstruments", WrapperNamespace="http://archfirst.org/bfoms/referencedataservice.wsdl", IsWrapped=true)]
    public partial class GetInstrumentsRequest {
        
        public GetInstrumentsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInstrumentsResponse", WrapperNamespace="http://archfirst.org/bfoms/referencedataservice.wsdl", IsWrapped=true)]
    public partial class GetInstrumentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfoms/referencedataservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Instrument", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Instrument[] Instrument;
        
        public GetInstrumentsResponse() {
        }
        
        public GetInstrumentsResponse(Instrument[] Instrument) {
            this.Instrument = Instrument;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReferenceDataWebServiceChannel : Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LookupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LookupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.Instrument Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.Instrument)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetInstrumentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetInstrumentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Instrument[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Instrument[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReferenceDataWebServiceClient : System.ServiceModel.ClientBase<Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService>, Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService {
        
        private BeginOperationDelegate onBeginLookupDelegate;
        
        private EndOperationDelegate onEndLookupDelegate;
        
        private System.Threading.SendOrPostCallback onLookupCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetInstrumentsDelegate;
        
        private EndOperationDelegate onEndGetInstrumentsDelegate;
        
        private System.Threading.SendOrPostCallback onGetInstrumentsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ReferenceDataWebServiceClient() {
        }
        
        public ReferenceDataWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReferenceDataWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReferenceDataWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReferenceDataWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<LookupCompletedEventArgs> LookupCompleted;
        
        public event System.EventHandler<GetInstrumentsCompletedEventArgs> GetInstrumentsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService.BeginLookup(Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLookup(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginLookup(string Symbol, System.AsyncCallback callback, object asyncState) {
            Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupRequest inValue = new Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupRequest();
            inValue.Symbol = Symbol;
            return ((Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService)(this)).BeginLookup(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupResponse Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService.EndLookup(System.IAsyncResult result) {
            return base.Channel.EndLookup(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.Instrument EndLookup(System.IAsyncResult result) {
            Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupResponse retVal = ((Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService)(this)).EndLookup(result);
            return retVal.Instrument;
        }
        
        private System.IAsyncResult OnBeginLookup(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Symbol = ((string)(inValues[0]));
            return this.BeginLookup(Symbol, callback, asyncState);
        }
        
        private object[] OnEndLookup(System.IAsyncResult result) {
            Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.Instrument retVal = this.EndLookup(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLookupCompleted(object state) {
            if ((this.LookupCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LookupCompleted(this, new LookupCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LookupAsync(string Symbol) {
            this.LookupAsync(Symbol, null);
        }
        
        public void LookupAsync(string Symbol, object userState) {
            if ((this.onBeginLookupDelegate == null)) {
                this.onBeginLookupDelegate = new BeginOperationDelegate(this.OnBeginLookup);
            }
            if ((this.onEndLookupDelegate == null)) {
                this.onEndLookupDelegate = new EndOperationDelegate(this.OnEndLookup);
            }
            if ((this.onLookupCompletedDelegate == null)) {
                this.onLookupCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLookupCompleted);
            }
            base.InvokeAsync(this.onBeginLookupDelegate, new object[] {
                        Symbol}, this.onEndLookupDelegate, this.onLookupCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService.BeginGetInstruments(Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetInstruments(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetInstruments(System.AsyncCallback callback, object asyncState) {
            Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsRequest inValue = new Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsRequest();
            return ((Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService)(this)).BeginGetInstruments(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsResponse Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService.EndGetInstruments(System.IAsyncResult result) {
            return base.Channel.EndGetInstruments(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private Instrument[] EndGetInstruments(System.IAsyncResult result) {
            Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsResponse retVal = ((Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService)(this)).EndGetInstruments(result);
            return retVal.Instrument;
        }
        
        private System.IAsyncResult OnBeginGetInstruments(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetInstruments(callback, asyncState);
        }
        
        private object[] OnEndGetInstruments(System.IAsyncResult result) {
            Instrument[] retVal = this.EndGetInstruments(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetInstrumentsCompleted(object state) {
            if ((this.GetInstrumentsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetInstrumentsCompleted(this, new GetInstrumentsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetInstrumentsAsync() {
            this.GetInstrumentsAsync(null);
        }
        
        public void GetInstrumentsAsync(object userState) {
            if ((this.onBeginGetInstrumentsDelegate == null)) {
                this.onBeginGetInstrumentsDelegate = new BeginOperationDelegate(this.OnBeginGetInstruments);
            }
            if ((this.onEndGetInstrumentsDelegate == null)) {
                this.onEndGetInstrumentsDelegate = new EndOperationDelegate(this.OnEndGetInstruments);
            }
            if ((this.onGetInstrumentsCompletedDelegate == null)) {
                this.onGetInstrumentsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetInstrumentsCompleted);
            }
            base.InvokeAsync(this.onBeginGetInstrumentsDelegate, null, this.onEndGetInstrumentsDelegate, this.onGetInstrumentsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService CreateChannel() {
            return new ReferenceDataWebServiceClientChannel(this);
        }
        
        private class ReferenceDataWebServiceClientChannel : ChannelBase<Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService>, Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService {
            
            public ReferenceDataWebServiceClientChannel(System.ServiceModel.ClientBase<Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLookup(Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Lookup", _args, callback, asyncState);
                return _result;
            }
            
            public Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupResponse EndLookup(System.IAsyncResult result) {
                object[] _args = new object[0];
                Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupResponse _result = ((Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupResponse)(base.EndInvoke("Lookup", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetInstruments(Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetInstruments", _args, callback, asyncState);
                return _result;
            }
            
            public Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsResponse EndGetInstruments(System.IAsyncResult result) {
                object[] _args = new object[0];
                Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsResponse _result = ((Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsResponse)(base.EndInvoke("GetInstruments", _args, result)));
                return _result;
            }
        }
    }

    public interface IReferenceDataServiceAsync : ReferenceDataWebService
    {
        void GetInstrumentsAsync();
        void LookupAsync(string Symbol);

        event EventHandler<GetInstrumentsCompletedEventArgs> GetInstrumentsCompleted;
        event EventHandler<LookupCompletedEventArgs> LookupCompleted;
    }

    [Export(typeof(IReferenceDataServiceAsync))]
    [PartCreationPolicy(CreationPolicy.NonShared)]
    public partial class ReferenceDataWebServiceClient : IReferenceDataServiceAsync
    {
    }
}
