//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://archfirst.org/bfexch/referencedataservice.wsdl", ConfigurationName="ReferenceDataServiceReference.ReferenceDataWebService")]
    public interface ReferenceDataWebService {
        
        // CODEGEN: Parameter 'Instrument' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="Lookup", ReplyAction="http://archfirst.org/bfexch/referencedataservice.wsdl/ReferenceDataWebService/Loo" +
            "kupResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Instrument")]
        Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupResponse Lookup(Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="Lookup", ReplyAction="http://archfirst.org/bfexch/referencedataservice.wsdl/ReferenceDataWebService/Loo" +
            "kupResponse")]
        System.IAsyncResult BeginLookup(Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupRequest request, System.AsyncCallback callback, object asyncState);
        
        Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupResponse EndLookup(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'Instrument' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="GetInstruments", ReplyAction="http://archfirst.org/bfexch/referencedataservice.wsdl/ReferenceDataWebService/Get" +
            "InstrumentsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Instrument")]
        Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsResponse GetInstruments(Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetInstruments", ReplyAction="http://archfirst.org/bfexch/referencedataservice.wsdl/ReferenceDataWebService/Get" +
            "InstrumentsResponse")]
        System.IAsyncResult BeginGetInstruments(Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsRequest request, System.AsyncCallback callback, object asyncState);
        
        Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsResponse EndGetInstruments(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://archfirst.org/bfexch/referencedataservice.wsdl")]
    public partial class Instrument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string symbolField;
        
        private string nameField;
        
        private string exchangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
                this.RaisePropertyChanged("Symbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Exchange {
            get {
                return this.exchangeField;
            }
            set {
                this.exchangeField = value;
                this.RaisePropertyChanged("Exchange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Lookup", WrapperNamespace="http://archfirst.org/bfexch/referencedataservice.wsdl", IsWrapped=true)]
    public partial class LookupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfexch/referencedataservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Symbol;
        
        public LookupRequest() {
        }
        
        public LookupRequest(string Symbol) {
            this.Symbol = Symbol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LookupResponse", WrapperNamespace="http://archfirst.org/bfexch/referencedataservice.wsdl", IsWrapped=true)]
    public partial class LookupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfexch/referencedataservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.Instrument Instrument;
        
        public LookupResponse() {
        }
        
        public LookupResponse(Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.Instrument Instrument) {
            this.Instrument = Instrument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInstruments", WrapperNamespace="http://archfirst.org/bfexch/referencedataservice.wsdl", IsWrapped=true)]
    public partial class GetInstrumentsRequest {
        
        public GetInstrumentsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInstrumentsResponse", WrapperNamespace="http://archfirst.org/bfexch/referencedataservice.wsdl", IsWrapped=true)]
    public partial class GetInstrumentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://archfirst.org/bfexch/referencedataservice.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Instrument", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Instrument[] Instrument;
        
        public GetInstrumentsResponse() {
        }
        
        public GetInstrumentsResponse(Instrument[] Instrument) {
            this.Instrument = Instrument;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReferenceDataWebServiceChannel : Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LookupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LookupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.Instrument Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.Instrument)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetInstrumentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetInstrumentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Instrument[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Instrument[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReferenceDataWebServiceClient : System.ServiceModel.ClientBase<Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService>, Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService {
        
        private BeginOperationDelegate onBeginLookupDelegate;
        
        private EndOperationDelegate onEndLookupDelegate;
        
        private System.Threading.SendOrPostCallback onLookupCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetInstrumentsDelegate;
        
        private EndOperationDelegate onEndGetInstrumentsDelegate;
        
        private System.Threading.SendOrPostCallback onGetInstrumentsCompletedDelegate;
        
        public ReferenceDataWebServiceClient() {
        }
        
        public ReferenceDataWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReferenceDataWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReferenceDataWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReferenceDataWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<LookupCompletedEventArgs> LookupCompleted;
        
        public event System.EventHandler<GetInstrumentsCompletedEventArgs> GetInstrumentsCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupResponse Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService.Lookup(Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupRequest request) {
            return base.Channel.Lookup(request);
        }
        
        public Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.Instrument Lookup(string Symbol) {
            Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupRequest inValue = new Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupRequest();
            inValue.Symbol = Symbol;
            Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupResponse retVal = ((Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService)(this)).Lookup(inValue);
            return retVal.Instrument;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService.BeginLookup(Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLookup(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLookup(string Symbol, System.AsyncCallback callback, object asyncState) {
            Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupRequest inValue = new Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupRequest();
            inValue.Symbol = Symbol;
            return ((Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService)(this)).BeginLookup(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupResponse Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService.EndLookup(System.IAsyncResult result) {
            return base.Channel.EndLookup(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.Instrument EndLookup(System.IAsyncResult result) {
            Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.LookupResponse retVal = ((Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService)(this)).EndLookup(result);
            return retVal.Instrument;
        }
        
        private System.IAsyncResult OnBeginLookup(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Symbol = ((string)(inValues[0]));
            return this.BeginLookup(Symbol, callback, asyncState);
        }
        
        private object[] OnEndLookup(System.IAsyncResult result) {
            Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.Instrument retVal = this.EndLookup(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLookupCompleted(object state) {
            if ((this.LookupCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LookupCompleted(this, new LookupCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LookupAsync(string Symbol) {
            this.LookupAsync(Symbol, null);
        }
        
        public void LookupAsync(string Symbol, object userState) {
            if ((this.onBeginLookupDelegate == null)) {
                this.onBeginLookupDelegate = new BeginOperationDelegate(this.OnBeginLookup);
            }
            if ((this.onEndLookupDelegate == null)) {
                this.onEndLookupDelegate = new EndOperationDelegate(this.OnEndLookup);
            }
            if ((this.onLookupCompletedDelegate == null)) {
                this.onLookupCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLookupCompleted);
            }
            base.InvokeAsync(this.onBeginLookupDelegate, new object[] {
                        Symbol}, this.onEndLookupDelegate, this.onLookupCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsResponse Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService.GetInstruments(Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsRequest request) {
            return base.Channel.GetInstruments(request);
        }
        
        public Instrument[] GetInstruments() {
            Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsRequest inValue = new Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsRequest();
            Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsResponse retVal = ((Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService)(this)).GetInstruments(inValue);
            return retVal.Instrument;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService.BeginGetInstruments(Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetInstruments(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetInstruments(System.AsyncCallback callback, object asyncState) {
            Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsRequest inValue = new Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsRequest();
            return ((Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService)(this)).BeginGetInstruments(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsResponse Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService.EndGetInstruments(System.IAsyncResult result) {
            return base.Channel.EndGetInstruments(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Instrument[] EndGetInstruments(System.IAsyncResult result) {
            Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.GetInstrumentsResponse retVal = ((Bullsfirst.InterfaceOut.Oms.ReferenceDataServiceReference.ReferenceDataWebService)(this)).EndGetInstruments(result);
            return retVal.Instrument;
        }
        
        private System.IAsyncResult OnBeginGetInstruments(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetInstruments(callback, asyncState);
        }
        
        private object[] OnEndGetInstruments(System.IAsyncResult result) {
            Instrument[] retVal = this.EndGetInstruments(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetInstrumentsCompleted(object state) {
            if ((this.GetInstrumentsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetInstrumentsCompleted(this, new GetInstrumentsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetInstrumentsAsync() {
            this.GetInstrumentsAsync(null);
        }
        
        public void GetInstrumentsAsync(object userState) {
            if ((this.onBeginGetInstrumentsDelegate == null)) {
                this.onBeginGetInstrumentsDelegate = new BeginOperationDelegate(this.OnBeginGetInstruments);
            }
            if ((this.onEndGetInstrumentsDelegate == null)) {
                this.onEndGetInstrumentsDelegate = new EndOperationDelegate(this.OnEndGetInstruments);
            }
            if ((this.onGetInstrumentsCompletedDelegate == null)) {
                this.onGetInstrumentsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetInstrumentsCompleted);
            }
            base.InvokeAsync(this.onBeginGetInstrumentsDelegate, null, this.onEndGetInstrumentsDelegate, this.onGetInstrumentsCompletedDelegate, userState);
        }
    }
}
